### ISSUE TITLE
Pod creation fails on Fedora25

### ISSUE THREAD

**Issue by psuriset** [cri-o/cri-o-ansible#4]
crioctl pod run --config test/testdata/sandbox_config.json
Creating the pod sandbox failed: rpc error: code = 2 desc = failed to create network for container redhat.test.crio-podsandbox1-1-infra in sandbox e346d8c8dbbee173b796de12a946590ca5bd5bafc29dff44852525a06800e76f: cni config uninitialized

Kernel: 4.11.3-200.fc25.x86_64
Fedora25
disabled selinux

**Comment by runcom** [comment]
What do you have inside /etc/cni/net.d and /opt/bin/cni ? The playbook should have created those, seems like you're not running the playbook??

**Comment by psuriset** [comment]
https://gist.github.com/psuriset/3e1f27296ce547724e35f4e254b9e016

**Comment by runcom** [comment]
Could you show me what's inside /etc/cni/net.d and /opt/cni/bin ?

**Comment by psuriset** [comment]
Looks like nothing is there inside /etc/cni/net.d and /opt/cni/bin ?

**Comment by runcom** [comment]
@psuriset are you on IRC?

**Comment by runcom** [comment]
@psuriset are you sure /opt/cni/bin is empty? https://github.com/cri-o/cri-o-ansible/blob/master/cri-o.yml#L164 installs binaries in there. It's correct /etc/cni/net.d being empty, CRI-O doesn't add network conf, kubernetes or openshift does. I'm going to close this since CRI-O isn't mean to be run with `crioctl`, rather, you have to use it with kubernetes or openshift

**Comment by runcom** [comment]
https://github.com/cri-o/cri-o-ansible#what-is-cri-o-ansible-not-doing
